import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import sympy
from regression_benchmark_functions import Imstepf_funcs,Nguyen_funcs
import importlib



"""

Goal of program:
    Read hall of fame .csv files generated by PySR for each function (use pandas), and graph each function against the true value ...
    in the main directory (residuals)
    (10/14/2024) - it would be good to STORE these values in a dictionary somewhere to be used later in the program
    Also calculate NMSE, MSE and Absolute Error
    Also graph Total Error vs Complexity (mess with axes)
    Also, compare against linear regression

To write:
    Use Pandas to open csv's ..
    use SymPy to read the functions inside the csv's ..
    use RegEx
        ^hall_of_fame_.*\.csv 
        matches
        hall_of_fame_2024-10-07_124744.825.csv (and everything else that starts with hall_of_fame and ends with .csv)
 
"""
def retrieveTrueFunction(dirpath):
    # extract the functions name from directory path
    folderName = os.path.basename(os.path.normpath(dirpath))
    # extract just the function's name
    funcName = '_'.join(folderName.split('_')[:2]) # assuming all functions following "Name_F#"
    return funcName

def importTrueFunction(funcName):
    # import the  correct function from regression_benchmark_functions.py
    regression_benchmarks = importlib.import_module('regression_benchmark_functions')
    trueFunction = getattr(regression_benchmarks,funcName)
    return trueFunction

def pdEvaluate(dirpath, filepath):
    # join filepaths and also fix the path (using / and \ interchangeably)
    wholepath = os.path.normpath(os.path.join(dirpath,filepath))
    #wholepath = os.path.normpath(filepath)
    #print(wholepath)

    # create dataframe with this csv to be manipulated
    hof_df = pd.read_csv(wholepath)
    '''
    From here, we want to find the "true" function that matches this .csv to compare against,
    then store all of the data in a dictionary (or df) to be returned.
    '''
    # get true function name
    trueFunctionName = retrieveTrueFunction(dirpath)
    print(f"True Function: {trueFunctionName}")

    # import true function from name
    trueFunction = importTrueFunction(trueFunctionName)
    print(f"Imported Function: {trueFunction}")


    

basedir = "C:/Users/brand/Documents/Python Scripts/pysr_code/datasets/RBFs-n-oos-(-1,1,20)"

os.chdir(basedir)


########### find hall of fame csv's ###################
pattern = re.compile(r"^hall_of_fame_.*\.csv")

matching_files = []

for dirpath, dirnames, filenames in os.walk(basedir):
    for filename in filenames:
        if pattern.match(filename):
            # run residuals function here
            pdcsv = pdEvaluate(dirpath, filename) ###### <--------- RESUME CODING HERE
            #############################
            full_path = os.path.join(dirpath, filename)
            matching_files.append(full_path)
            

# Print matching files
#for file in matching_files:
#    print(file)

# Create a DataFrame with the matching files
#filepath_df = pd.DataFrame({"file_path": matching_files})
#print(filepath_df)
########################################################

#### can also run tests using only one part of the matching files: 
#pdEvaluate(dirpath, filename)